### ISSUE TITLE
why x.unsqueeze(dim=0)

### ISSUE THREAD

**Issue by 4fee8fea** [amazon-research/mix-generation#1]
Hi,

Thanks for your great work and make it public.

I wonder why [`.unsqueeze(dim=0)`](https://github.com/amazon-research/mix-generation/blob/6e2a5ecf74ab63d166a77d69579216687887d802/mixgen.py#L13) is used here.  It seems that this is not a necessary operation.

Best

**Comment by bryanyzhu** [comment]
Hi thank you for raising it, we have removed the unnecessary part.
