### ISSUE TITLE
Percentage of images using MixGen

### ISSUE THREAD

**Issue by 1024er** [amazon-research/mix-generation#2]
The second page says "Given a minibatch of B randomly sampled image-text pairs, MixGen replaces the first M training samples with the newly generated pairs... By default, we set M = B/4 in Algorithm 1", And the fifth page says "a minibatch will contain 384 existing samples and 128 new image-text pairs."

But I look inside the code, MixGen replaces the whole batch with the newly generated pairs.

![image](https://user-images.githubusercontent.com/17399203/187323663-d67f4140-3103-42b6-964a-9961fe44c116.png)

Is there a sampling operation behind it to select M newly generated pairs?

**Comment by haoshuai714** [comment]
We provide two MixGen variants in the mixgen.py file.
(1)mixgen_batch:We replace the whole batch with the newly generated pairs.
(2)mixgen:We replace  the first M training samples with the newly generated pairs
